# Generated by Django 5.0.3 on 2024-05-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome_social', models.CharField(max_length=200)),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=2)),
                ('cor', models.CharField(max_length=10)),
                ('num_casa', models.CharField(max_length=6)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=50)),
                ('sp', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('religiao', models.CharField(max_length=50)),
                ('nome_mae', models.CharField(blank=True, max_length=200)),
                ('nome_pai', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(max_length=14)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
    ]
